spring.application.name=AgendaAcademica
spring.datasource.url=jdbc:mysql://localhost:3306/bd_agendaa
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Grok / xAI API Configuration
grok.api.key=
grok.api.url=https://api.xai.com/v1/chat/completions
